school/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .import management
from .import staff
from .import principal
from .import parent

app_name = 'school'

urlpatterns = [
    path('add_student/<str:pk>/', management.add_student, name='add_student'),
    path('add_student_education_history', management.add_student_education,name='add_student_education_history'),
    path('add_student_emmergency_contact', management.add_student_emergency,name='add_student_emmergency_contact'),
    path('add_student_medical', management.add_student_medical,name='add_student_medical'),
    path('add_student_immunization', management.add_student_immunization, name='add_student_immunization'),
    path('next', management.nexts,name='next'),
    path('delete_student/<str:pk>/', management.delete_student, name='delete_student'),
    path('student_profile/<str:pk>/',management.student_profile, name='student_profile'),
    path('edit_student/<str:pk>/',management.edit_student, name='edit_student'),
   
    path('edit_student_edu/<str:pk>/', management.edit_student_education, name='edit_student_edu'),
    path('edit_student_emmergency/<str:pk>/',management.edit_student_emmergency, name='edit_student_emmergency'),
    path('edit_student_medical/<str:pk>/',management.edit_student_medical, name='edit_student_medical'),
    path('edit_student_immunization/<str:pk>/',management.edit_student_immunization, name='edit_student_immunization'),
    
    path('delete_student_education/<str:pk>/',management.delete_student_education, name='delete_student_education'),
    path('delete_student_emmergency/<str:pk>/',management.delete_student_emmergency, name='delete_student_emmergency'),
    path('delete_student_medical/<str:pk>/',management.delete_student_medical, name='delete_student_medical'),
    path('delete_student_immunization/<str:pk>/',management.delete_student_immunization,         name='delete_student_immunization'),
    
    path('add_profile_student_education/<str:pk>/',management.add_profile_student_education, name='add_profile_student_education'),
    path('add_profile_student_emmergency/<str:pk>/',
         management.add_profile_student_emmergency, name='add_profile_student_emmergency'),
    path('add_profile_student_medical/<str:pk>/',
         management.add_profile_student_medical, name='add_profile_student_medical'),
    path('add_profile_student_immunization/<str:pk>/',
         management.add_profile_student_immunization, name='add_profile_student_immunization'),
    
    
    path('add_staff', management.add_staff, name='add_staff'),
    path('add_staff_education_history', management.add_staff_education,name='add_staff_education_history'),
    path('add_staff_work_experience', management.add_staff_work_experience,name='add_staff_work_experience'),
    path('add_staff_emmergency_contact', management.add_staff_emmergency_contact,name='add_staff_emmergency_contact'),
    path('staff_profile/<str:pk>/',management.staff_profile, name='staff_profile'),
    path('staffnext', management.staffnexts, name='staffnext'),
    path('manage_staff', management.manage_staff, name='manage_staff'),
    
    path('edit_staff_edu/<str:pk>/',management.edit_staff_education, name='edit_staff_edu'),
    path('edit_staff_contact/<str:pk>/',management.edit_staff_emmergency, name='edit_staff_contact'),
    path('edit_staff_work/<str:pk>/',management.edit_staff_work, name='edit_staff_work'),
    
    path('delete_staff_education/<str:pk>/',management.delete_staff_education, name='delete_staff_education'),
    path('delete_staff_emmergency/<str:pk>/',management.delete_staff_emmergency, name='delete_staff_emmergency'),
    path('delete_staff_work/<str:pk>/',management.delete_staff_work, name='delete_staff_work'),
    
    path('add_profile_staff_education/<str:pk>/',management.add_profile_staff_education, name='add_profile_staff_education'),
    path('add_profile_staff_emmergency/<str:pk>/',
         management.add_profile_staff_emmergency, name='add_profile_staff_emmergency'),
    path('add_profile_staff_work/<str:pk>/',
         management.add_profile_staff_work, name='add_profile_staff_work'),
    path('edit_staff/<str:pk>/', management.edit_staff, name='edit_staff'),

    
    path('add_parent', management.add_parent, name='add_parent'),
    path('manage_parent', management.manage_parent, name='manage_parent'),
    path('manage_student', management.manage_student, name='manage_student'),
    path('edit_parent/<str:pk>/', management.edit_parent, name='edit_parent'),
    path('delete_parent/<str:pk>/', management.delete_parent, name='delete_parent'),
    
    
    path('add_academicyear', management.add_academicyear, name='add_academicyear'),
    path('manage_academicyear', management.manage_academicyear,name='manage_academicyear'),
    path('edit_academicyear/<str:pk>/',management.edit_academicyear, name='edit_academicyear'),
    path('delete_academic_year/<str:pk>/',management.delete_academic_year, name='delete_academic_year'),
    
    path('add_academicterm', management.add_academicterm, name='add_academicterm'),
    path('manage_academicterm', management.manage_academicterm, name='manage_academicterm'),
    path('edit_academicterm/<str:pk>/',management.edit_academicterm, name='edit_academicterm'),
    path('delete_academic_term/<str:pk>/',management.delete_academic_term, name='delete_academic_term'),
    
    path('add_class', management.add_class, name='add_class'),
    path('manage_class', management.manage_class, name='manage_class'),
    path('edit_class/<str:pk>/',management.edit_class, name='edit_class'),
    path('delete_class/<str:pk>/', management.delete_class, name='delete_class'),
    
    path('add_subject/<str:pk>/', management.add_subject, name='add_subject'),
    path('edit_subject/<str:pk>/', management.edit_subject, name='edit_subject'),
    path('delete_subject/<str:pk>/',management.delete_subject, name='delete_subject'),
    path('manage_subject', management.manage_subject, name='manage_subject'),
    
    path('create_attendance', staff.create_attendance,name='create_attendance'),
    path('manage_attendance', staff.manage_attendance, name='manage_attendance'),
    path('delete_attendance/<str:pk>/',staff.delete_attendance, name='delete_attendance'),
    path('edit_attendance/<str:pk>/',staff.edit_attendance, name='edit_attendance'),
    path('take_attendance/<str:pk>/',staff.take_attendance, name='take_attendance'),
    path('present/<str:pk>/',staff.present, name='present'),
    path('absent/<str:pk>/', staff.absent, name='absent'),
    path('closing', staff.closing, name='closing'),
    path('view_attendance/<str:pk>/',staff.view_attendance, name='view_attendance'),
    path('epresent/<str:pk>/', staff.epresent, name='epresent'),
    path('eabsent/<str:pk>/', staff.eabsent, name='eabsent'),
    
    path('create_results', staff.create_results, name='create_results'),
    path('manage_results', staff.manage_results, name='manage_results'),
    path('delete_results/<str:pk>/',staff.delete_results, name='delete_results'),
    path('edit_results/<str:pk>/',staff.edit_results, name='edit_results'),
    
    path('add_results/<str:pk>/', staff.add_results, name='add_results'),
    path('stud_results/<str:pk>/', staff.stud_results, name='stud_results'),
    path('subject_results/<str:pk>/',staff.subject_results, name='subject_results'),
    path('create_student_results/<str:pk>/',staff.create_student_results, name='create_student_results'),
    path('resultclose', staff.resultclose, name='resultclose'),
    path('view_student_result/<str:pk>/',staff.view_student_result, name='view_student_result'),
    path('print_student_result/<str:pk>/',
         staff.print_student_result, name='print_student_result'),
    path('add_promotion/<str:pk>/',staff.add_promotion, name='add_promotion'),
    
    
    path('create_bill', management.create_bill, name='create_bill'),
    path('manage_bill', management.manage_bill, name='manage_bill'),
    path('add_bill/<str:pk>/',management.add_bill, name='add_bill'),
    path('view_bill/<str:pk>/',management.view_bill, name='view_bill'),
    path('generate_student_bill/<str:pk>/',
         management.generate_student_bill, name='generate_student_bill'),
    path('parentbill/<str:pk>/', parent.parentbill,name='parentbill'),
    path('create_payroll', management.create_payroll, name='create_payroll'),
    path('manage_payroll',management.manage_payroll, name='manage_payroll'),
    path('run_payroll', management.run_payroll, name='run_payroll'),
    path('account_code', management.account_code, name='account_code'),
    path('editaccount_code/<str:pk>/',management.editaccount_code, name='editaccount_code'),
    path('manage_account_code', management.manage_account_code,
         name='manage_account_code'),
    
    path('manage_pv', management.manage_pv, name='manage_pv'),
    path('create_pv', management.create_pv, name='create_pv'),
    path('add_pv_details/<str:pk>/',management.add_pv_details, name='add_pv_details'),
    path('view_pv/<str:pk>/', management.view_pv, name='view_pv'),
    path('approve_pvs/<str:pk>/', management.approve_pvs, name='approve_pvs'),
    path('cancel_pvs/<str:pk>/', management.cancel_pvs, name='cancel_pvs'),
    
    path('make_payment/<str:pk>/', management.make_payment, name='make_payment'),
    
    path('totalrevenue', management.allrevenue, name="totalrevenue"),
    path('totalexpense', management.allexpenses, name="totalexpense"),
    path('income&expenditure', management.income_expenditure,
         name="income&expenditure"),
    path('yearlyincome&expenditure', management.stats_income_expenditure,
         name="yearlyincome&expenditure"),
    path('accountreceivable', management.account_receivable,
         name="accountreceivable"),
    path('manage_fees', management.manage_fees,name="manage_fees"),
    
    path('broadcast', management.broadcast, name="broadcast"),

school_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from school_management_system import settings
from django.conf.urls.static import static
from school import views

urlpatterns = [
    path('', views.login_view, name='log'),
    path('logouts', views.logout_request,name='logouts'),
    path('school/', include('school.urls', namespace='school')),
    path('admin/', admin.site.urls),
]

# urlpatterns += static(settings.MEDIA_URL,
#                       document_root=settings.MEDIA_ROOT)

templates/hod_template/footer.html
<footer class="main-footer">
      <strong>Copyright &copy; {% now "Y" %}, <a href="https://vijaythapa.com.np">Vijay Thapa</a>.</strong> 
      All rights reserved.
      <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0
      </div>
    </footer>

templates/hod_template/immunization.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content ">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">

                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <div class="text-center">
                            <img class="profile-user-img img-fluid img-circle" src=" {{students.profile_pic.url}}"
                                alt="User profile picture">
                        </div>

                        <h3 class="profile-username text-center">{{students.Surname }} {{ students.firstname}}</h3>
                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b>Class</b> <a class="float-right">{{students.course_id}}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Gender</b> <a class="float-right">{{students.gender}}</a>
                            </li>
                            <li class="list-group-item">
                                <b>Date of Birth</b> <a class="float-right">{{students.dob}}</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

                <!-- About Me Box -->
                <div class="card card-primary card-outline">

                    <!-- /.card-header -->
                    <div class="card-body">
                        <strong><i class="fas fa-user mr-1"></i> Parents</strong>

                        <p class="text-muted">
                            {{ students.parent_id.father_name}} <br> {{ students.parent_id.mother_name}}
                        </p>


                        <hr>

                        <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

                        <p class="text-muted">{{students.residential_address}}</p>

                        <hr>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>

            <div class="col-9 novalidate">

                <div class="row">
                    <div class="col-lg">
                        <div class="card ">
                            <div class="card-header bg-primary color-palette">
                                <h3 class="card-title">Immunization</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="POST" enctype="multipart/form-data" novalidate>
                                {% csrf_token %}
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col-3">
                                            {{ form.age|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-3">
                                            {{ form.immunisation|as_crispy_field }}
                                        </div>
                                        <div class="form-group col-6">
                                            {{ form.givendate|as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group col">
                                            <button type="submit" class="btn btn-sm bg-primary color-palette">Submit</button>
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col ">
                                        </div>
                                        <div class="form-group col float-left">
                                            <a class='btn btn-sm btn-warning' href="{% url 'school:next' %}">Finish</a>
                                        </div>
                                    </div>
                                </div>


                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
</div>


</div>



{% endblock %}

templates/hod_template/manage_parent.html
{% extends "base.html" %}
{% block content%}

<div class="col-lg">
    <div class="card card-primary card-outline">
        <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table table-bordered table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1"
                                        colspan="1" aria-sort="ascending"
                                        aria-label="Rendering engine: activate to sort column descending">ID
                                    </th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Father's Name</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending"> Contact</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Engine version: activate to sort column ascending">Mother's Name</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Engine version: activate to sort column ascending">Contact</th>
                                   
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for parent in parent_list %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td class="sorting_1">{{parent.id}}</td>
                                    <td>{{parent.father_name}}</td>
                                    <td>{{parent.father_phone}}</td>
                                    <td>{{parent.mother_name}}</td>
                                    <td>{{parent.mother_phone}}</td>
                                    <td>
                                      <a class="btn btn-sm btn-warning" href="{% url 'school:edit_parent' parent.id %}">Edit</a>
                                    <a class="btn btn-sm btn-danger" href="{% url 'school:delete_parent' parent.id %}">Delete</a>
                                    <a class="btn btn-sm btn-primary" href="{% url 'school:add_student' parent.id %}">Add Student</a>
                                    </td>
                                </tr>

                                {% endfor %}

                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% endblock %}

templates/hod_template/manage_pv.html
{% extends "base.html" %}
{% block content%}

<div class="col-12">
    <div class="card card-primary card-outline ">
        <div class="card-body">
            <a class="btn btn-primary btn-sm mb-1" href="{% url 'school:create_pv' %}">Create Pv</a>
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table  table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead class="">
                                <tr role="row">

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Description</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Total Amount</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending">Status</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending">Date Created</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for p in pv %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td>{{ p.description }}</td>
                                    <td>{{ p.amount }}</td>
                                    
                                    {% if p.status == 'pending' %}
                                       <td><span class= "badge bg-warning">{{p.status}}</span></td>
                                    {% elif p.status == 'approved' %}
                                        <td><span class= "badge bg-primary">{{p.status}}</span></td>
                                    {% else %}
                                        <td><span class= "badge bg-danger">{{p.status}}</span></td>
                                    {% endif %}
                                        
                                    <td>{{ p.created_date }}</td>
                                    
                                    {% if p.status == 'approved' %}
                                    <td>
                                        <a class="btn btn-sm btn-success" href="{% url 'school:view_pv' p.id %}">View</a>
                                    </td>
                                    {% else %}
                                        <td>
                                            <a class="btn btn-sm btn-primary" href="{% url 'school:add_pv_details' p.id %}">Add Details</a>
                                            <a class="btn btn-sm btn-success" href="{% url 'school:view_pv' p.id %}">View</a>
                                        </td>
                                    {% endif %}
                                        
                                   
                                </tr>

                                {% endfor %}

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% endblock %}

templates/hod_template/pv_details.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="content ">
    <div class="container-fluid">
        <div class="row">

            <div class="col-10 mx-auto">
                <div class="card-header">
                    <h3 class="text-center">
                        Pv Details
                    </h3>
                </div>
                <div class="card card-primary card-outline">
                    <div>
                    <dl class="row ml-5">
                        
                        <dt class="col-sm-3">PV Number:</dt>
                        <dd class="col-sm-3">{{ pvs.id }}</dd>
                        <dt class="col-sm-3">Description:</dt>
                        <dd class="col-sm-3">{{ pvs.description }}</dd>
                        <dt class="col-sm-3">Pv Amount:</dt>
                        <dd class="col-sm-3">{{ pvs.amount }}</dd>
                        <dt class="col-sm-3">Status: </dt>
                        {% if pvs.status == "pending" %}
                        <dd class="col-sm-3"><span class="badge bg-warning">{{ pvs.status }}</span></dd>
                        {% elif pvs.status == "approved" %}
                        <dd class="col-sm-3"><span class="badge bg-primary">{{ pvs.status }}</span></dd>
                        {% else %}
                        <dd class="col-sm-3"><span class="badge bg-danger">{{ pvs.status }}</span></dd>
                        {% endif %}
                        <dt class="col-sm-3">Pv Date:</dt>
                        <dd class="col-sm-3">{{ pvs.created_date }}</dd>
                    </dl>
                    </div>
                        
                    
                    
                </div>
                <div class="row">
                    <div class="col-lg">
                        <div class="card card-primary card-outline">
                            <div class="card-body">
                            {% for group in user.groups.all %} {% if group.name == 'principal' %}
                                {% if pvs.status == 'pending' %}
                                    <a class="btn btn-sm btn-primary mb-1" href="{% url 'school:approve_pvs' pvs.id %}">Approve Pv</a>
                                    <a class="btn btn-sm btn-danger mb-1 ml-3" href="{% url 'school:cancel_pvs' pvs.id %}">Cancelled Pv</a>
                                {% else %}
                                    
                                {% endif %}
                            {% endif %}
                            {% endfor %}
                                
                                <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <table id="example3" class="table table-bordered table-striped table-hover"
                                                role="grid" aria-describedby="example2_info">
                                                <thead>
                                                    <tr role="row">
                                                        <th class="sorting" tabindex="0" aria-controls="example2"
                                                            rowspan="1" colspan="1"
                                                            aria-label="Browser: activate to sort column ascending">
                                                            Description</th>

                                                        <th class="sorting" tabindex="0" aria-controls="example2"
                                                            rowspan="1" colspan="1"
                                                            aria-label="Browser: activate to sort column ascending">
                                                            Amount GH&#8373</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for p in pvs_detail %}
                                                    </tr>
                                                    <tr role="row" class="odd">
                                                        <td>{{p.description }}</td>
                                                        <td>{{p.amount }}</td>
                                                    </tr>
                                                    {% endfor %}

                                                </tbody>
                                                <tfoot>
                                                    <tr role="row">

                                                        <th class="sorting_asc" tabindex="0" aria-controls="example2"
                                                            rowspan="1" colspan="1" aria-sort="ascending"
                                                            aria-label="Rendering engine: activate to sort column descending">
                                                            <b>TOTAL: </b>
                                                        </th>
                                                        <th class="sorting_asc" tabindex="0" aria-controls="example2"
                                                            rowspan="1" colspan="1" aria-sort="ascending"
                                                            aria-label="Rendering engine: activate to sort column descending">
                                                            <b> {{ detail_total.cc}}</b>
                                                        </th>
                                                </tfoot>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
</div>






{% endblock %}