school/urls.py
    path('edit_student/<str:pk>/',management.edit_student, name='edit_student'),
   
    path('edit_student_edu/<str:pk>/', management.edit_student_education, name='edit_student_edu'),
    path('edit_student_emmergency/<str:pk>/',management.edit_student_emmergency, name='edit_student_emmergency'),
    path('edit_student_medical/<str:pk>/',management.edit_student_medical, name='edit_student_medical'),
    path('edit_student_immunization/<str:pk>/',management.edit_student_immunization, name='edit_student_immunization'),
    
    path('delete_student_education/<str:pk>/',management.delete_student_education, name='delete_student_education'),
    path('delete_student_emmergency/<str:pk>/',management.delete_student_emmergency, name='delete_student_emmergency'),
    path('delete_student_medical/<str:pk>/',management.delete_student_medical, name='delete_student_medical'),
    path('delete_student_immunization/<str:pk>/',management.delete_student_immunization,         name='delete_student_immunization'),
    
    path('add_profile_student_education/<str:pk>/',management.add_profile_student_education, name='add_profile_student_education'),
    path('add_profile_student_emmergency/<str:pk>/',
         management.add_profile_student_emmergency, name='add_profile_student_emmergency'),
    path('add_profile_student_medical/<str:pk>/',
         management.add_profile_student_medical, name='add_profile_student_medical'),
    path('add_profile_student_immunization/<str:pk>/',
         management.add_profile_student_immunization, name='add_profile_student_immunization'),
    
    
    path('add_staff', management.add_staff, name='add_staff'),
    path('add_staff_education_history', management.add_staff_education,name='add_staff_education_history'),
    path('add_staff_work_experience', management.add_staff_work_experience,name='add_staff_work_experience'),
    path('add_staff_emmergency_contact', management.add_staff_emmergency_contact,name='add_staff_emmergency_contact'),
    path('staff_profile/<str:pk>/',management.staff_profile, name='staff_profile'),
    path('staffnext', management.staffnexts, name='staffnext'),
    path('manage_staff', management.manage_staff, name='manage_staff'),
    
    path('edit_staff_edu/<str:pk>/',management.edit_staff_education, name='edit_staff_edu'),
    path('edit_staff_contact/<str:pk>/',management.edit_staff_emmergency, name='edit_staff_contact'),
    path('edit_staff_work/<str:pk>/',management.edit_staff_work, name='edit_staff_work'),
    
    path('delete_staff_education/<str:pk>/',management.delete_staff_education, name='delete_staff_education'),
    path('delete_staff_emmergency/<str:pk>/',management.delete_staff_emmergency, name='delete_staff_emmergency'),
    path('delete_staff_work/<str:pk>/',management.delete_staff_work, name='delete_staff_work'),
    
    path('add_profile_staff_education/<str:pk>/',management.add_profile_staff_education, name='add_profile_staff_education'),
    path('add_profile_staff_emmergency/<str:pk>/',
         management.add_profile_staff_emmergency, name='add_profile_staff_emmergency'),
    path('add_profile_staff_work/<str:pk>/',
         management.add_profile_staff_work, name='add_profile_staff_work'),
    path('edit_staff/<str:pk>/', management.edit_staff, name='edit_staff'),

    
    path('add_parent', management.add_parent, name='add_parent'),
    path('manage_parent', management.manage_parent, name='manage_parent'),
    path('manage_student', management.manage_student, name='manage_student'),
    path('edit_parent/<str:pk>/', management.edit_parent, name='edit_parent'),
    path('delete_parent/<str:pk>/', management.delete_parent, name='delete_parent'),
    
    
    path('add_academicyear', management.add_academicyear, name='add_academicyear'),
    path('manage_academicyear', management.manage_academicyear,name='manage_academicyear'),
    path('edit_academicyear/<str:pk>/',management.edit_academicyear, name='edit_academicyear'),
    path('delete_academic_year/<str:pk>/',management.delete_academic_year, name='delete_academic_year'),
    
    path('add_academicterm', management.add_academicterm, name='add_academicterm'),
    path('manage_academicterm', management.manage_academicterm, name='manage_academicterm'),
    path('edit_academicterm/<str:pk>/',management.edit_academicterm, name='edit_academicterm'),
    path('delete_academic_term/<str:pk>/',management.delete_academic_term, name='delete_academic_term'),
    
    path('add_class', management.add_class, name='add_class'),
    path('manage_class', management.manage_class, name='manage_class'),
    path('edit_class/<str:pk>/',management.edit_class, name='edit_class'),
    path('delete_class/<str:pk>/', management.delete_class, name='delete_class'),
    
    path('add_subject/<str:pk>/', management.add_subject, name='add_subject'),
    path('edit_subject/<str:pk>/', management.edit_subject, name='edit_subject'),
    path('delete_subject/<str:pk>/',management.delete_subject, name='delete_subject'),
    path('manage_subject', management.manage_subject, name='manage_subject'),
    
    path('create_attendance', staff.create_attendance,name='create_attendance'),
    path('manage_attendance', staff.manage_attendance, name='manage_attendance'),
    path('delete_attendance/<str:pk>/',staff.delete_attendance, name='delete_attendance'),
    path('edit_attendance/<str:pk>/',staff.edit_attendance, name='edit_attendance'),
    path('take_attendance/<str:pk>/',staff.take_attendance, name='take_attendance'),
    path('present/<str:pk>/',staff.present, name='present'),
    path('absent/<str:pk>/', staff.absent, name='absent'),
    path('closing', staff.closing, name='closing'),
    path('view_attendance/<str:pk>/',staff.view_attendance, name='view_attendance'),
    path('epresent/<str:pk>/', staff.epresent, name='epresent'),
    path('eabsent/<str:pk>/', staff.eabsent, name='eabsent'),
    
    path('create_results', staff.create_results, name='create_results'),
    path('manage_results', staff.manage_results, name='manage_results'),
    path('delete_results/<str:pk>/',staff.delete_results, name='delete_results'),
    path('edit_results/<str:pk>/',staff.edit_results, name='edit_results'),
    
    path('add_results/<str:pk>/', staff.add_results, name='add_results'),
    path('stud_results/<str:pk>/', staff.stud_results, name='stud_results'),
    path('subject_results/<str:pk>/',staff.subject_results, name='subject_results'),
    path('create_student_results/<str:pk>/',staff.create_student_results, name='create_student_results'),
    path('resultclose', staff.resultclose, name='resultclose'),
    path('view_student_result/<str:pk>/',staff.view_student_result, name='view_student_result'),
    path('print_student_result/<str:pk>/',
         staff.print_student_result, name='print_student_result'),
    path('add_promotion/<str:pk>/',staff.add_promotion, name='add_promotion'),
    
    
    path('create_bill', management.create_bill, name='create_bill'),
    path('manage_bill', management.manage_bill, name='manage_bill'),
    path('add_bill/<str:pk>/',management.add_bill, name='add_bill'),
    path('view_bill/<str:pk>/',management.view_bill, name='view_bill'),
    path('generate_student_bill/<str:pk>/',
         management.generate_student_bill, name='generate_student_bill'),
    path('parentbill/<str:pk>/', parent.parentbill,name='parentbill'),
    path('create_payroll', management.create_payroll, name='create_payroll'),
    path('manage_payroll',management.manage_payroll, name='manage_payroll'),
    path('run_payroll', management.run_payroll, name='run_payroll'),
    path('account_code', management.account_code, name='account_code'),
    path('editaccount_code/<str:pk>/',management.editaccount_code, name='editaccount_code'),
    path('manage_account_code', management.manage_account_code,
         name='manage_account_code'),
    
    path('manage_pv', management.manage_pv, name='manage_pv'),
    path('create_pv', management.create_pv, name='create_pv'),
    path('add_pv_details/<str:pk>/',management.add_pv_details, name='add_pv_details'),
    path('view_pv/<str:pk>/', management.view_pv, name='view_pv'),
    path('approve_pvs/<str:pk>/', management.approve_pvs, name='approve_pvs'),
    path('cancel_pvs/<str:pk>/', management.cancel_pvs, name='cancel_pvs'),
    
    path('make_payment/<str:pk>/', management.make_payment, name='make_payment'),
    
    path('totalrevenue', management.allrevenue, name="totalrevenue"),
    path('totalexpense', management.allexpenses, name="totalexpense"),
    path('income&expenditure', management.income_expenditure,
         name="income&expenditure"),
    path('yearlyincome&expenditure', management.stats_income_expenditure,
         name="yearlyincome&expenditure"),
    path('accountreceivable', management.account_receivable,
         name="accountreceivable"),
    path('manage_fees', management.manage_fees,name="manage_fees"),
    
    path('broadcast', management.broadcast, name="broadcast"),
    path('manage_sms', management.manage_sms, name="manage_sms"),
    
    path('dashboard', management.dashboard, name="dashboard"),
    path('staff_dashboard', staff.staff_dashboard, name="staff_dashboard"),
    path('principaldashboard', principal.principaldashboard,name="principaldashboard"),
    path('parentdashboard', parent.parentdashboard,name="parentdashboard"),
    
    
    path('change-password/', views.change_password, name='change_password'),
    path('reminders', management.reminders, name='reminders'),
    
    path('load_term', management.load_term, name='load_term'),
    
    
    
    path('viewing_results', staff.viewing_results, name='viewing_results'),
    path('add_resultss/<str:pk>/', staff.add_resultss, name='add_resultss'),
    path('print_student_results/<str:pk>/',
         staff.print_student_results, name='print_student_results'),
    path('view_student_results/<str:pk>/',
         staff.view_student_results, name='view_student_results'),
    

school_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from school_management_system import settings
from django.conf.urls.static import static
from school import views

urlpatterns = [
    path('', views.login_view, name='log'),
    path('logouts', views.logout_request,name='logouts'),
    path('school/', include('school.urls', namespace='school')),
    path('admin/', admin.site.urls),
]

# urlpatterns += static(settings.MEDIA_URL,
#                       document_root=settings.MEDIA_ROOT)

templates/staff_template/create_results.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-9 mx-auto novalidate">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg">
                    <div class="card ">
                        <div class="card-header bg-primary color-palette">
                            <h3 class="card-title">Class</h3>
                        </div>
                        <form role="form" method="POST" novalidate>
                            {% csrf_token %}
                            <div class="card-body">
                                <div class="row">
                                    <div class="form-group col">
                                        {{ form.class_id|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group col">
                                        <button type="submit" class="btn bg-primary color-palette">Submit</button>
                                    </div>
                                </div>

                            </div>
                    </div>
                </div>

                </form>
            </div>
        </div>
    </div>
</div>

</div>
{% endblock %}

templates/staff_template/manage_attendance.html
{% extends "base.html" %}
{% block content%}

<div class="col-12">
    <div class="card card-primary card-outline ">
        <div class="card-body ">
             {% for group in user.groups.all %} {% if group.name == 'teacher' %}
                <a class="btn btn-primary btn-sm mb-1" href="{% url 'school:create_attendance' %}">Create Attendance</a>
            {% endif %}
            {% endfor %}
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table  table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead class="">
                                <tr role="row">

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Academic Year</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Academic Term Name</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending">Class</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending">Attendance Date</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for acadamic in academic_term %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td>{{ acadamic.session_year_id }}</td>
                                    <td>{{ acadamic.term_year_id }}</td>
                                    <td>{{ acadamic.class_id.class_name }}</td>
                                    <td>{{ acadamic.attendance_date}}</td>

                                    {% for group in user.groups.all %} {% if group.name == 'teacher' %}

                                    <td>
                                        <a class="btn btn-sm btn-warning"
                                            href="{% url 'school:edit_attendance' acadamic.id %}">Edit</a>
                                        <a class="btn btn-sm btn-danger"
                                            href="{% url 'school:delete_attendance' acadamic.id  %}">Delete</a>
                                        <a class="btn btn-sm btn-primary" href="{% url 'school:take_attendance' acadamic.id %}">Take Attendance</a>
                                        <a class="btn btn-sm btn-success" href="{% url 'school:view_attendance' acadamic.id %}">View</a>
                                    </td>
                                    {% else %}
                                    <td>
                                        <a class="btn btn-sm btn-primary" href="{% url 'school:view_attendance' acadamic.id %}">View</a>
                                    </td>
                                    {% endif %}
                                    {% endfor %}
                                </tr>

                                {% endfor %}

                            </tbody>
                           
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% endblock %}

templates/staff_template/manage_results.html
{% extends "base.html" %}
{% block content%}

<div class="col-lg">
    <div class="card card-primary card-outline">
        <div class="card-body">
            {% for group in user.groups.all %} {% if group.name == 'teacher' %}
            <a class="btn btn-primary btn-sm mb-1" href="{% url 'school:create_results' %}">Create  Results</a>
            {% endif %}
            {% endfor %}
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table table-bordered table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead class="">
                                <tr role="row">

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Academic Year</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Academic Term Name</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending">Class</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Platform(s): activate to sort column ascending">Result Date</th>
                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="CSS grade: activate to sort column ascending">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for acadamic in academic_term %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td>{{ acadamic.session_year_id }}</td>
                                    <td>{{ acadamic.term_year_id }}</td>
                                    <td>{{ acadamic.class_id.class_name }}</td>
                                    <td>{{ acadamic.created_at}}</td>



                                    <td>
                                       
                                        {% for group in user.groups.all %} {% if group.name == 'parent' %}
                                             <a class="btn btn-sm btn-primary" href="{% url 'school:stud_results' acadamic.id %}">View Results</a>
                                        {% else %}
                                            <a class="btn btn-sm btn-warning" href="{% url 'school:edit_results' acadamic.id %}">Edit</a>
                                            <a class="btn btn-sm btn-danger" href="{% url 'school:delete_results' acadamic.id %}">Delete</a>
                                            <a class="btn btn-sm btn-primary" href="{% url 'school:add_results' acadamic.id %}">Add Results</a>
                                   
                                            
                                        {% endif %}
                                    {% endfor %}
                                            
                                    </td>
                                </tr>

                                {% endfor %}

                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% endblock %}

templates/staff_template/result_subject_list.html
{% extends "base.html" %}
{% block content%}

<div class="col-lg">
    <div class="card card-primary card-outline">
        <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table table-bordered table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead>
                                <tr role="row">

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Class Subjects</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Add Results</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for s in subj %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td>{{ s.subject_name }}</td>

                                    <td>
                                        <a id="reply_button" class="btn btn-sm btn-primary ml-3" href="{% url 'school:create_student_results' s.id %}">Record Score</a>
                                    </td>

                                </tr>

                                {% endfor %}

                            </tbody>
                            <tfoot>


                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="form-group col">
                    <a class="btn btn-sm btn-primary " href="{% url 'school:resultclose' %}">Finish</a>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>

{% endblock %}

templates/staff_template/take_attendance.html
{% extends "base.html" %}
{% block content%}

<div class="col-lg">
    <div class="card card-primary card-outline">
        <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table table-bordered table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead>
                                <tr role="row">

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Class Sudents</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Attendance</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for s in stu %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td>{{ s.Surname  }} {{ s.firstname }}</td>
                                    
                                    <td >
                                        <a id="reply_button" class="btn btn-sm btn-primary ml-3" href="{% url 'school:present' s.id %}">Present</a>
                                       <a id="reply_button"  class="btn btn-sm btn-danger ml-3" href="{% url 'school:absent' s.id %}">Absent</a>
                                       
                                    </td>
                                  
                                </tr>

                                {% endfor %}

                            </tbody>
                            <tfoot>
                                
                               
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
        <div class="row">
            <div class="form-group col">
                <a class="btn btn-sm btn-primary " href="{% url 'school:closing' %}">Finish</a>
            </div>
        </div>
        </div>
    </div><!-- /.card -->
</div>
<script>
    $(document).ready(function () {
       
        $(document).on("click", "#reply_button", function () {
            //Disabling the Button while data is being saved in Server
            $(this).attr("disabled", "disabled")
            })


        })
</script>
{% endblock %}

templates/staff_template/take_resultss.html
{% extends "base.html" %}
{% block content%}
{% for group in user.groups.all %} {% if group.name == 'parent' %}
<div class="col-lg">
    <div class="card card-primary card-outline">
        <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table table-bordered table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead>
                                <tr role="row">

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Class Students</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for s in stu %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td>{{ s.Surname }} {{ s.firstname }}</td>

                                    <td>
                                        {% for group in user.groups.all %} {% if group.name == 'teacher' %}
                                        <a id="reply_button" class="btn btn-sm btn-primary ml-3"
                                            href="{% url 'school:subject_results' s.id %}">Add Results</a>

                                        <a id="reply_button" class="btn btn-sm btn-warning ml-3"
                                            href="{% url 'school:add_promotion' s.id %}">Promotion and Remarks</a>
                                        <a id="reply_button" href="{% url 'school:print_student_result' s.id %}"
                                            rel="noopener" target="_blank" class="btn btn-sm btn-danger ml-3"><i
                                                class="fas fa-print"></i>
                                            Print</a>

                                        {% else %}
                                        <a id="reply_button" class="btn btn-sm btn-success ml-3"
                                            href="{% url 'school:view_student_result' s.id %}">View
                                            Results</a>
                                        <a class="btn btn-sm btn-danger"
                                            href="{% url 'school:print_student_result' s.id %}" rel="noopener"
                                            target="_blank" class="btn btn-default"><i class="fas fa-print"></i>
                                            Print</a>
                                        {% endif %}
                                        {% endfor %}

                                    </td>


                                </tr>

                                {% endfor %}

                            </tbody>
                            <tfoot>


                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="form-group col">
                    <a class="btn btn-sm btn-primary " href="{% url 'school:manage_results' %}">Finish</a>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% else %}

<div class="col-lg">
    <div class="card card-primary card-outline">
        <div class="card-body">
            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table id="example2" class="table table-bordered table-striped table-hover" role="grid"
                            aria-describedby="example2_info">
                            <thead>
                                <tr role="row">

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Class Students</th>

                                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1"
                                        aria-label="Browser: activate to sort column ascending">Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for s in stu %}
                                </tr>
                                <tr role="row" class="odd">
                                    <td>{{ s.Surname }} {{ s.firstname }}</td>

                                    <td>
                                       
                                        <a id="reply_button" class="btn btn-sm btn-success ml-3"
                                            href="{% url 'school:view_student_result' s.id %}">View
                                            Results</a>
                                        <a class="btn btn-sm btn-danger"
                                            href="{% url 'school:print_student_results' s.id %}" rel="noopener"
                                            target="_blank" class="btn btn-default"><i class="fas fa-print"></i>
                                            Print</a>
                                     

                                    </td>


                                </tr>

                                {% endfor %}

                            </tbody>
                            <tfoot>


                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="form-group col">
                    <a class="btn btn-sm btn-primary " href="{% url 'school:manage_results' %}">Finish</a>
                </div>
            </div>
        </div>
    </div><!-- /.card -->
</div>
{% endif %}
{% endfor %}
{% endblock %}